service: bice-vida-it-lab-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  api:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'